# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'circle.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from math import pi
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Circle(object):
    def submit(self):
        try:
            radius_test = self.Radius_edit.text()
            radius = float(radius_test)
            area =0
            area = pi * (radius)**2
            self.label_summary.setText(f"Total {area:.2f}")
        except:
            self.label_summary.setText(" Enter numeric value")


    def setupUi(self, Circle):
        Circle.setObjectName("Circle")
        Circle.resize(250, 259)
        self.centralwidget = QtWidgets.QWidget(Circle)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 20, 71, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 41, 16))
        self.label_2.setObjectName("label_2")
        self.Circle_button = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.submit())
        self.Circle_button.setGeometry(QtCore.QRect(100, 190, 56, 17))
        self.Circle_button.setObjectName("Circle_button")
        self.Radius_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.Radius_edit.setGeometry(QtCore.QRect(90, 70, 113, 20))
        self.Radius_edit.setObjectName("Radius_edit")
        self.label_summary = QtWidgets.QLabel(self.centralwidget)
        self.label_summary.setGeometry(QtCore.QRect(70, 119, 111, 41))
        self.label_summary.setText("")
        self.label_summary.setObjectName("label_summary")
        Circle.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Circle)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 250, 18))
        self.menubar.setObjectName("menubar")
        Circle.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Circle)
        self.statusbar.setObjectName("statusbar")
        Circle.setStatusBar(self.statusbar)

        self.retranslateUi(Circle)
        QtCore.QMetaObject.connectSlotsByName(Circle)

    def retranslateUi(self, Circle):
        _translate = QtCore.QCoreApplication.translate
        Circle.setWindowTitle(_translate("Circle", "MainWindow"))
        self.label.setText(_translate("Circle", "   Circle AREA"))
        self.label_2.setText(_translate("Circle", "Radius"))
        self.Circle_button.setText(_translate("Circle", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Circle = QtWidgets.QMainWindow()
    ui = Ui_Circle()
    ui.setupUi(Circle)
    Circle.show()
    sys.exit(app.exec_())
