# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from Triangle_P import *
from Circle_perimeter import *
from sw import *
from rectangle_perimeter import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sot(object):
    def submit(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_C1()
        self.ui.setupUi(self.window)
        self.window.show()

    def submit_2(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_TC()
        self.ui.setupUi(self.window)
        self.window.show()
    def submit_3(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_sw()
        self.ui.setupUi(self.window)
        self.window.show()
    def submit_4(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_fg()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, Sot):
        Sot.setObjectName("Sot")
        Sot.resize(277, 274)
        self.centralwidget = QtWidgets.QWidget(Sot)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 241, 51))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.submit())
        self.pushButton.setGeometry(QtCore.QRect(40, 80, 61, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.submit_2())
        self.pushButton_2.setGeometry(QtCore.QRect(170, 80, 56, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget,clicked =lambda: self.submit_3())
        self.pushButton_3.setGeometry(QtCore.QRect(40, 146, 61, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.submit_4())
        self.pushButton_4.setGeometry(QtCore.QRect(170, 146, 56, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        Sot.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Sot)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 277, 18))
        self.menubar.setObjectName("menubar")
        Sot.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Sot)
        self.statusbar.setObjectName("statusbar")
        Sot.setStatusBar(self.statusbar)

        self.retranslateUi(Sot)
        QtCore.QMetaObject.connectSlotsByName(Sot)

    def retranslateUi(self, Sot):
        _translate = QtCore.QCoreApplication.translate
        Sot.setWindowTitle(_translate("Sot", "MainWindow"))
        self.label.setText(_translate("Sot", "    SELECT SHAPES TO CALCULATE PERIMETER"))
        self.pushButton.setText(_translate("Sot", "Circle"))
        self.pushButton_2.setText(_translate("Sot", "Triangle"))
        self.pushButton_3.setText(_translate("Sot", "Square"))
        self.pushButton_4.setText(_translate("Sot", "Rectangle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Sot = QtWidgets.QMainWindow()
    ui = Ui_Sot()
    ui.setupUi(Sot)
    Sot.show()
    sys.exit(app.exec_())
