# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from rectangle import *
from triangle import *
from circle import *
from square import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Bot(object):
    def submit(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Circle()
        self.ui.setupUi(self.window)
        self.window.show()

    def submit_rectangle(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_RECT()
        self.ui.setupUi(self.window)
        self.window.show()
    def submit_triangle(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_triangle_1()
        self.ui.setupUi(self.window)
        self.window.show()

    def submit_square(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_SWQ()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, Bot):
        Bot.setObjectName("Bot")
        Bot.resize(313, 309)
        self.centralwidget = QtWidgets.QWidget(Bot)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.submit())
        self.pushButton.setGeometry(QtCore.QRect(70, 90, 56, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.submit_triangle())
        self.pushButton_2.setGeometry(QtCore.QRect(170, 90, 56, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.submit_square())
        self.pushButton_3.setGeometry(QtCore.QRect(70, 190, 56, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.submit_rectangle())
        self.pushButton_4.setGeometry(QtCore.QRect(170, 190, 56, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(104, 30, 61, 21))
        self.label.setObjectName("label")
        Bot.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Bot)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 313, 18))
        self.menubar.setObjectName("menubar")
        Bot.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Bot)
        self.statusbar.setObjectName("statusbar")
        Bot.setStatusBar(self.statusbar)

        self.retranslateUi(Bot)
        QtCore.QMetaObject.connectSlotsByName(Bot)

    def retranslateUi(self, Bot):
        _translate = QtCore.QCoreApplication.translate
        Bot.setWindowTitle(_translate("Bot", "MainWindow"))
        self.pushButton.setText(_translate("Bot", "Circle"))
        self.pushButton_2.setText(_translate("Bot", "Triangle"))
        self.pushButton_3.setText(_translate("Bot", "Square"))
        self.pushButton_4.setText(_translate("Bot", "Rectangle"))
        self.label.setText(_translate("Bot", "      SHAPES"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Bot = QtWidgets.QMainWindow()
    ui = Ui_Bot()
    ui.setupUi(Bot)
    Bot.show()
    sys.exit(app.exec_())
