# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rectangle.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from math import pi
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RECT(object):
    def rectangle_button(self):
        try:
            length_test = self.lineEdit.text()
            width_test = self.lineEdit_2.text()

            length = float(length_test)
            width = float(width_test)
            area = 0
            area = length * width
            self.label_summary.setText(f"Total {area:.2f}")
        except:
            self.label_summary.setText(" Enter properly radius")
    def setupUi(self, RECT):
        RECT.setObjectName("RECT")
        RECT.resize(246, 256)
        self.centralwidget = QtWidgets.QWidget(RECT)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 10, 101, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 51, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 51, 21))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.rectangle_button())
        self.pushButton.setGeometry(QtCore.QRect(90, 180, 56, 17))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(70, 50, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 90, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_summary = QtWidgets.QLabel(self.centralwidget)
        self.label_summary.setGeometry(QtCore.QRect(70, 119, 111, 41))
        self.label_summary.setText("")
        self.label_summary.setObjectName("label_summary")
        RECT.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RECT)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 246, 18))
        self.menubar.setObjectName("menubar")
        RECT.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RECT)
        self.statusbar.setObjectName("statusbar")
        RECT.setStatusBar(self.statusbar)

        self.retranslateUi(RECT)
        QtCore.QMetaObject.connectSlotsByName(RECT)

    def retranslateUi(self, RECT):
        _translate = QtCore.QCoreApplication.translate
        RECT.setWindowTitle(_translate("RECT", "MainWindow"))
        self.label.setText(_translate("RECT", "   RECTANGLE AREA"))
        self.label_2.setText(_translate("RECT", "   Length"))
        self.label_3.setText(_translate("RECT", "   Width "))
        self.pushButton.setText(_translate("RECT", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RECT = QtWidgets.QMainWindow()
    ui = Ui_RECT()
    ui.setupUi(RECT)
    RECT.show()
    sys.exit(app.exec_())
