# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rectangle_perimeter.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fg(object):
    def rectangle_button(self):
        try:
            length_test = self.lineEdit.text()
            width_test = self.lineEdit_2.text()

            length = float(length_test)
            width = float(width_test)
            perimeter = 0
            perimeter = 2*(length + width)
            self.label_4.setText(f"Total {perimeter:.2f}")
        except:
            self.label_4.setText(" Enter either the length or width properly")
    def setupUi(self, fg):
        fg.setObjectName("fg")
        fg.resize(306, 264)
        self.centralwidget = QtWidgets.QWidget(fg)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 10, 131, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 35, 10))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 35, 10))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 70, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 100, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 140, 71, 31))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.rectangle_button())
        self.pushButton.setGeometry(QtCore.QRect(110, 200, 56, 17))
        self.pushButton.setObjectName("pushButton")
        fg.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(fg)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 306, 18))
        self.menubar.setObjectName("menubar")
        fg.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(fg)
        self.statusbar.setObjectName("statusbar")
        fg.setStatusBar(self.statusbar)

        self.retranslateUi(fg)
        QtCore.QMetaObject.connectSlotsByName(fg)

    def retranslateUi(self, fg):
        _translate = QtCore.QCoreApplication.translate
        fg.setWindowTitle(_translate("fg", "MainWindow"))
        self.label.setText(_translate("fg", "RECTANGLE PERIMETER"))
        self.label_2.setText(_translate("fg", "Length "))
        self.label_3.setText(_translate("fg", "Width "))
        self.pushButton.setText(_translate("fg", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fg = QtWidgets.QMainWindow()
    ui = Ui_fg()
    ui.setupUi(fg)
    fg.show()
    sys.exit(app.exec_())
