# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'square.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SWQ(object):
    def button(self):
        try:
            side_test = self.lineEdit.text()

            side = float(side_test)

            area = side **2
            self.label_3.setText(f"Total {area:.2f}")
        except:
            self.label_3.setText(" Enter the side properly")
    def setupUi(self, SWQ):
        SWQ.setObjectName("SWQ")
        SWQ.resize(268, 262)
        self.centralwidget = QtWidgets.QWidget(SWQ)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 10, 91, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 35, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 70, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 129, 61, 41))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget,clicked =lambda: self.button())
        self.pushButton.setGeometry(QtCore.QRect(100, 200, 56, 17))
        self.pushButton.setObjectName("pushButton")
        SWQ.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SWQ)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 268, 18))
        self.menubar.setObjectName("menubar")
        SWQ.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SWQ)
        self.statusbar.setObjectName("statusbar")
        SWQ.setStatusBar(self.statusbar)

        self.retranslateUi(SWQ)
        QtCore.QMetaObject.connectSlotsByName(SWQ)

    def retranslateUi(self, SWQ):
        _translate = QtCore.QCoreApplication.translate
        SWQ.setWindowTitle(_translate("SWQ", "MainWindow"))
        self.label.setText(_translate("SWQ", "   SQUARE AREA"))
        self.label_2.setText(_translate("SWQ", "Side"))
        self.pushButton.setText(_translate("SWQ", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SWQ = QtWidgets.QMainWindow()
    ui = Ui_SWQ()
    ui.setupUi(SWQ)
    SWQ.show()
    sys.exit(app.exec_())
